export type {
  CaptionCatalogCategory,
  CaptionCatalogEntry,
  CaptionCatalogResponse,
  CaptionProjectFile,
  CaptionStyleCatalogItem,
  CaptionsCdnBaseManifest,
  LocalCdnBaseManifest,
  LocalStyleManifest,
  LocalStylePackage,
  PresetOrigin,
  PresetSource,
  StylePreset,
  StylePreviewColors,
  StylesLocalState,
  StylesSyncResult,
  StylesSyncStatus,
} from "./types";
export { EMPTY_DEFINITION } from "./types";

export {
  colorIdsFromDefinition,
  downloadMasterTemplate,
  downloadStylePackage,
  ensureDefinitionForStyle,
  clearCaptionControlsCache,
  hasLocalMasterTemplate,
  isPresetDirty,
  isPresetValuesDirty,
  makeOrigin,
  presetSwatchColors,
  matchPresetByStyleName,
  previewFromValues,
  refreshStylePackageIfRemoteChanged,
  refreshCaptionControlsIfRemoteNewer,
  syncCaptionStyles,
  valuesEqual,
} from "./sync";
export {
  CaptionApiError,
  authErrorMessage,
  captionsCdnBaseManifestUrl,
  downloadCaptionProject,
  fetchCaptionControls,
  fetchCaptionStylesCatalog,
  fetchCaptionsCatalog,
  fetchCaptionsCdnBaseManifest,
  flattenCatalog,
  hashArrayBuffer,
  pickProjectFile,
  resolveControlsUrl,
  resolveMediaUrl,
  CAPTIONS_CDN_VERSION_FOLDER,
} from "./api";
export type { CaptionDownloadResult } from "./api";
export {
  loadCdnBaseManifest,
  loadLocalPackage,
  loadLocalState,
  loadUserControlsDefinition,
  removeLocalPackage,
  removeUserControls,
  removeUserPreset,
  saveCdnBaseManifest,
  saveLocalPackage,
  saveLocalState,
  saveUserControls,
  upsertUserPreset,
} from "./localStore";
export {
  getCdnBaseManifestPath,
  getMasterPackageDir,
  getStylePackageDir,
  getStylesDir,
  getStylesRoot,
  getUserControlsPath,
  getUserStyleDir,
  getUserStylesDir,
  styleIdToDirName,
  MASTER_AEP_FILE,
  MASTER_MOGRT_FILE,
  MASTER_STYLE_ID,
} from "./paths";
export {
  acquireAndApplyPreset,
  acquirePresetProject,
  applyPresetProjectInHost,
  getLocalStyleAssetPaths,
} from "./applyPipeline";
export type {
  AcquirePresetStatus,
  ApplyStyleProjectResult,
  LocalStyleAssetPaths,
  PreparedPresetProject,
} from "./applyPipeline";
